version: '3.9'
services:
  adguard:
    networks:
      adguard-wireguard:
        ipv4_address: 10.255.0.2
    labels:
      traefik.docker.network: runtipi_tipi_main_network

networks:
  adguard-wireguard:
    driver: bridge
    name: adguard-wireguard
    ipam:
      config:
       - subnet: 10.255.0.0/16 